---
title: "2016 Election Prediction Project Description"
author: "Christopher Oh"
date: 2018-08-29
output: 
  github_document
---

### Motivation

The result of the 2016 US presidential election came as a surprise to many, but perhaps
not to Ford Fessenden, who published a piece title [Donald Trump¡¯s Big Bet on Less Educated Whites](https://www.nytimes.com/interactive/2016/11/07/us/how-trump-can-win.html) a day before
the election day.

Fascinated by his keen insight, I decided to retrace the steps the author took that led to 
his conclusion.

### Goal

To reproduce the map depitcting the estimated laregest voting-age population demographics in
each county that later revealed to closely resemble the election result.

Achieved by leveraging the latest __tidyverse__ packages for advanced data wrangling
and the __sf__ package for spatial visualization.

### Thank you

I would like to thank Bill Behrman, the director of [Stanford Data Lab](https://datalab.stanford.edu/), 
for providing me with an inspiration and close guidance throughout the duration of the project.